name: cd
on:
  workflow_run:
    workflows: ["ci"]
    branches-ignore: [master]
    types:
      - completed
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
       is_pr: false
    secrets: inherit
    needs: [test]