name: ci
on:
  pull_request:
  push:
    branches:
      - main
# env:
#   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test:
    uses: ./.github/workflows/.test.yml
  push-docker:
    uses: ./.github/workflows/.docker-push.yml
    with:
      is_pr: "${{ github.ref != 'refs/heads/main' }}"
    secrets: inherit
    needs: [test]

  #  lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Go
  #       uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
  #       with:
  #         go-version: "1.19"
  #         cache: true

  #     - name: ci/check-style
  #       run: make check-style